version: "3.9"

services:
  web:
    build:
      context: .
      target: prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    restart: unless-stopped

  test:
    build:
      context: .
      target: test
      args:
        VITE_API_URL: ${VITE_API_URL}
